#Leer en https://editor.swagger.io/
openapi: 3.0.4
info:
  title: Catálogo de Roles.
  description: Representación de catálogo de roles.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /roles:
    get:
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    catalogo_roles:
      type: string
      enum:
        - "R0001: ACCIONISTA"
        - "R0002: ACREDITADO"
        - "R0003: ACREDITANTE"
        - "R0004: ACREEDOR"
        - "R0005: ADHERENTE"
        - "R0006: ADJUDICATARIO"
        - "R0007: ADMINISTRADOR UNICO"
        - "R0008: ADQUIRENTE"
        - "R0009: ALBACEA"
        - "R0010: APODERADO"
        - "R0011: ARRENDADOR"
        - "R0012: ARRENDATARIO"
        - "R0013: ASOCIACION"
        - "R0014: ASOCIADO"
        - "R0015: ASOCIADO DIRECTOR"
        - "R0016: ASOCIANTE"
        - "R0017: BENEFICIARIO"
        - "R0018: CAUSAHABIENTE"
        - "R0019: CEDENTE"
        - "R0020: CESIONARIO"
        - "R0021: COLINDANTE"
        - "R0022: COMISARIO"
        - "R0023: COMODANTE"
        - "R0024: COMODATARIO"
        - "R0025: COMPARECIENTE"
        - "R0026: COMPRADOR"
        - "R0027: CONYUGE"
        - "R0028: CONYUGE DEL COMPRADOR"
        - "R0029: CONYUGE DEL VENDEDOR"
        - "R0030: CONYUGE SUPERSTITE"
        - "R0031: COOPERATIVA"
        - "R0032: DE CUJUS"
        - "R0033: DECLARANTE"
        - "R0034: DELEGADO ESPECIAL"
        - "R0035: DENOMINACION"
        - "R0036: DEPOSITANTE"
        - "R0037: DEPOSITARIO"
        - "R0038: DEUDOR"
        - "R0039: DIRECTOR GENERAL"
        - "R0040: DISTRIBUIDOR"
        - "R0041: DIVORCIANTE"
        - "R0042: DONANTE"
        - "R0043: DONATARIO"
        - "R0044: EMISOR"
        - "R0045: ENAJENANTE"
        - "R0046: ESCINDENTE"
        - "R0047: ESCINDIDA"
        - "R0048: FABRICANTE"
        - "R0049: FACTORADO"
        - "R0050: FACTORANTE"
        - "R0051: FIDEICOMISARIO"
        - "R0052: FIDEICOMITENTE"
        - "R0053: FIDUCIARIO"
        - "R0054: FUSIONADA"
        - "R0055: FUSIONANTE"
        - "R0056: GARANTE"
        - "R0057: GARANTE FIDUCIARIO"
        - "R0058: GARANTE HIPOTECARIO"
        - "R0059: GARANTE PRENDARIO"
        - "R0060: GERENTE"
        - "R0061: GESTOR"
        - "R0062: HEREDERO"
        - "R0063: INTERMEDIARIO"
        - "R0064: INTERPELANTE"
        - "R0065: JUEZ"
        - "R0066: LEGATARIO"
        - "R0067: LIQUIDADOR"
        - "R0068: MANDANTE"
        - "R0069: MANDATARIO"
        - "R0070: MENOR"
        - "R0071: MUTUANTE"
        - "R0072: MUTUATARIO"
        - "R0073: NUDO PROPIETARIO"
        - "R0074: OBLIGACIONISTA"
        - "R0075: OBLIGADO SOLIDARIO"
        - "R0076: OTORGANTE"
        - "R0077: PERMUTANTE"
        - "R0078: PODERDANTE"
        - "R0079: PRESIDENTE DE LA MESA DIRECTIVA"
        - "R0080: PRESIDENTE DEL ORGANO DE ADMINISTRACION"
        - "R0081: PRESTAMISTA"
        - "R0082: PRESTATARIO"
        - "R0083: PROMITENTE"
        - "R0084: PROPIETARIO"
        - "R0085: PROPIETARIO DEL PREDIO DOMINANTE"
        - "R0086: PROPIETARIO DEL PREDIO SIRVIENTE"
        - "R0087: RATIFICANTE"
        - "R0088: REPORTADO"
        - "R0089: REPORTADOR"
        - "R0090: REPRESENTANTE COMUN"
        - "R0091: REQUIRENTE"
        - "R0092: REVOCADO"
        - "R0093: REVOCANTE"
        - "R0094: SECRETARIO DEL ORGANO DE ADMINISTRACION"
        - "R0095: SOCIEDAD"
        - "R0096: SOCIO"
        - "R0097: SOCIO ADMINISTRADOR"
        - "R0098: SOLICITANTE"
        - "R0099: TENEDOR"
        - "R0100: TESORERO DEL ORGANO DE ADMINISTRACION"
        - "R0101: TESTADOR"
        - "R0102: TESTIGO"
        - "R0103: TRABAJADOR"
        - "R0104: TRANSMITENTE"
        - "R0105: TUTOR"
        - "R0106: USUFRUCTUARIO"
        - "R0107: VENDEDOR"
        - "R0108: VICEPRESIDENTE DEL ORGANO DE ADMINISTRACION"
        - "R0109: VOCAL DEL ORGANO DE ADMINISTRACION"
        - "R0110: ACCIONISTA UNICO"
        - "R0111: ACOMPAÑANTE"
        - "R0112: REPRESENTANTE"
        - "R0113: ADMINISTRADOR"
        - "R0114: AVAL"
        - "R0115: DELEGADO FIDUCIARIO"
        - "R0116: DIRECTOR"
        - "R0117: FIADOR"
        - "R0118: GERENTE GENERAL"
        - "R0119: PRESIDENTE DEL CONSEJO DE ADMINISTRACION"
        - "R0120: REPRESENTANTE LEGAL"
        - "R0121: SECRETARIO DEL CONSEJO DE ADMINISTRACION"
        - "R0122: SECRETARIO DE LA MESA DIRECTIVA"
        - "R0123: TESORERO DEL CONSEJO DE ADMINISTRACION"
        - "R0124: TESORERO DE LA MESA DIRECTIVA"
        - "R0125: VICEPRESIDENTE DEL CONSEJO DE ADMINISTRACION"
        - "R0126: VOCAL"
        - "R0127: ACREEDOR FIDUCIARIO"
        - "R0128: ACREEDOR HIPOTECARIO"
        - "R0129: ACREEDOR HIPOTECARIO EN PRIMER LUGAR"
        - "R0130: ACREEDOR HIPOTECARIO EN SEGUNDO LUGAR"
        - "R0131: APORTANTE"
        - "R0132: ASIGNATARIO"
        - "R0133: BANCO"
        - "R0134: COACREDITADO"
        - "R0135: COACREDITANTE"
        - "R0136: COHEREDERO"
        - "R0137: COMISARIO PROPIETARIO"
        - "R0138: COMISARIO SUPLENTE"
        - "R0139: CONDOMINO"
        - "R0140: CONSEJERO"
        - "R0141: CONSEJERO DEL ORGANO DE ADMINISTRACION"
        - "R0142: CONSEJERO INDEPENDIENTE"
        - "R0143: CONSEJERO PROPIETARIO DEL ORGANO DE ADMINISTRACION"
        - "R0144: CONSEJERO SUPLENTE DEL ORGANO DE ADMINISTRACION"
        - "R0145: CONTRALOR"
        - "R0146: CONYUGE DEL ENAJENANTE"
        - "R0147: CONYUGE DEL FIDEICOMITENTE"
        - "R0148: CONYUGE DEL MANDANTE"
        - "R0149: COORDINADOR"
        - "R0150: COPROPIETARIO"
        - "R0151: DELEGADO"
        - "R0152: DEUDOR (SU SUCESION)"
        - "R0153: DEUDOR SOLIDARIO"
        - "R0154: EJECUTOR"
        - "R0155: FIDEICOMISARIO A"
        - "R0156: FIDEICOMISARIO B"
        - "R0157: FIDEICOMISARIO C"
        - "R0158: FIDEICOMISARIO EN CUARTO LUGAR"
        - "R0159: FIDEICOMISARIO EN PRIMER LUGAR"
        - "R0160: FIDEICOMISARIO EN SEGUNDO LUGAR"
        - "R0161: FIDEICOMISARIO EN TERCER LUGAR"
        - "R0162: FIDEICOMITENTE A"
        - "R0163: FIDEICOMITENTE B"
        - "R0164: FIDEICOMITENTE EN PRIMER LUGAR"
        - "R0165: FIDEICOMITENTE EN SEGUNDO LUGAR"
        - "R0166: GERENTE ESPECIAL"
        - "R0167: GERENTE UNICO"
        - "R0168: INTERPRETE"
        - "R0169: INVITADO"
        - "R0170: MIEMBRO DEL COMITE DE AUDITORIA"
        - "R0171: MIEMBRO DEL COMITE TECNICO"
        - "R0172: MIEMBRO DEL CONSEJO DE VIGILANCIA"
        - "R0173: MIEMBRO DEL ORGANO DE ADMINISTRACION"
        - "R0174: MIEMBRO INDEPENDIENTE DEL ORGANO DE ADMINISTRACION"
        - "R0175: MIEMBRO PROPIETARIO DEL ORGANO DE ADMINISTRACION"
        - "R0176: MIEMBRO SUPLENTE DEL ORGANO DE ADMINISTRACION"
        - "R0177: NOTIFICADO"
        - "R0178: OBLIGADO MANCOMUNADO"
        - "R0179: OBLIGADO PRINCIPAL"
        - "R0180: PRESIDENTE"
        - "R0181: PRESIDENTE DEL COMITE TECNICO"
        - "R0182: PRESIDENTE SUPLENTE DEL ORGANO DE ADMINISTRACION"
        - "R0183: RENUNCIANTE"
        - "R0184: SECRETARIO DEL COMITE TECNICO"
        - "R0185: SECRETARIO NO MIEMBRO DEL ORGANO DE ADMINISTRACION"
        - "R0186: SECRETARIO SUPLENTE DEL ORGANO DE ADMINISTRACION"
        - "R0187: SINDICATO"
        - "R0188: SUBARRENDADOR"
        - "R0189: SUBARRENDATARIO"
        - "R0190: TESORERO DEL COMITE TECNICO"
        - "R0191: VICEPRESIDENTE DEL COMITE TECNICO"
        - "R0192: VOCAL DEL COMITE TECNICO"
        - "R0193: VOCAL SUPLENTE DEL ORGANO DE ADMINISTRACION"
        - "R050: OTRO"
