#Leer en https://editor.swagger.io/
openapi: 3.0.4
info:
  title: catálogo de Tipo de Personas
  description: Representación de Schema de catalogo de Tipo de Personas.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /tipo_personas:
    get:
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    catalogo_tipo_personas:
      type: string
      enum:
        - "PF: Persona Física Nacional vive en México. (Anexo3)"
        - "PFE: Persona Física Extranjera. (Anexo3)"
        - "PFEV: Persona Física Extranjera Visitante. (Anexo5)"
        - "PM: Persona Moral Nacional. (Anexo4)"
        - "PMDP: Persona Moral Derecho Público. (Anexo4Bis)"
        - "PMDPS: Persona Moral Derecho Público régimen simplificado. (Anexo7Bis)"
        - "PME: Persona Moral Extranjera. (Anexo6)"
        - "PMEF: Persona Moral Entidad Financiera. (Anexo9)"
        - "PMEM: Persona Moral Embajada, Consulados u Organismos Internacionales. (Anexo6Bis)"
        - "PMF: Persona Moral Fideicomisos. (Anexo8)"


