#Leer en https://editor.swagger.io/
openapi: 3.0.4
info:
  title: Schema de Actos
  description: Representación de Schema de actos.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /actos:
    get:
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    data_type_fecha:
      type: string
      format: date
      description: Fecha en formato YYYY-MM-DD. # NUEVO: Descripción más explícita
      example: "2023-10-15"
    catalogo_tipo_personas:
      type: string
      enum:
        - "PF: Persona Física Nacional vive en México. (Anexo3)"
        - "PFE: Persona Física Extranjera. (Anexo3)"
        - "PFEV: Persona Física Extranjera Visitante. (Anexo5)"
        - "PM: Persona Moral Nacional. (Anexo4)"
        - "PMDP: Persona Moral Derecho Público. (Anexo4Bis)"
        - "PMDPS: Persona Moral Derecho Público régimen simplificado. (Anexo7Bis)"
        - "PME: Persona Moral Extranjera. (Anexo6)"
        - "PMEF: Persona Moral Entidad Financiera. (Anexo9)"
        - "PMEM: Persona Moral Embajada, Consulados u Organismos Internacionales. (Anexo6Bis)"
        - "PMF: Persona Moral Fideicomisos. (Anexo8)"
    catalogo_actos:
      type: string
      enum:
        - "A0001: APEO Y DESLINDE"
        - "A0002: INMATRICULACION"
        - "A0003: ACTA DE EMISION DE TITULOS OPCIONALES"
        - "A0004: ACTA DE EMISION DE OBLIGACIONES"
        - "A0005: ACTA DE EMISION DE OBLIGACIONES SUBORDINADAS"
        - "A0006: ACTA DE EMISION DE OBLIGACIONES NO CONVERTIBLES EN ACCIONES"
    catalogo_roles:
      type: string
      enum:
        - "R0001: ACCIONISTA"
        - "R0002: ACREDITADO"
        - "R0003: ACREDITANTE"
        - "R0004: ACREEDOR"
        - "R0005: ADHERENTE"
        - "R0006: ADJUDICATARIO"
    representante:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        tipo_persona:
          $ref: '#/components/schemas/catalogo_tipo_personas'
        name_completo:
          type: string
          example: Jaun Mora Gonzalez
        firmante:
          type: boolean
          example: false
    compareciente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        id_catalogo_tipo_personas:
          $ref: '#/components/schemas/catalogo_tipo_personas'
        nombre_completo:
          type: string
          example: Alfoso Luna Gonzalez
        porcentaje:
          type: number
          format: double
          description: Porcentaje de participación en la sociedad. Debe ser con 6 decimales.
          example: 34.163415
        firmante:
          type: boolean
          example: false
        id_catalogo_roles:
          $ref: '#/components/schemas/catalogo_roles'
        representantes:
          type: array
          items:
            $ref: '#/components/schemas/representante'
    acto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        id_catalogo_actos:
          $ref: '#/components/schemas/catalogo_actos'
        comparecientes:
          type: array
          items:
            $ref: '#/components/schemas/compareciente'
    instrumento:
      type: object
      properties:
        protocolo:
          type: integer
          example: 9
        tipo_protocolo:
          type: string
          enum:
            - instrumentos
            - cotejos
        numero:
          type: integer
          example: 2344
        volumen:
          type: string
          example: 
          - "345"
          - "Volumen 1 Tomo 3"
          - "Tomo 4 Volumen 2"
        fechas:
          type: object
          properties:
            fecha_pase:
              $ref: '#/components/schemas/data_type_fecha'
            fecha_firma:
              $ref: '#/components/schemas/data_type_fecha'
            fecha_definitiva:
              $ref: '#/components/schemas/data_type_fecha'
        folios:      
          type: object
          properties:
            cantidad:
              type: integer
            utilizados:
              type: array
              items:
                type: integer
            inutilizados:
              type: array
              items:
                type: integer
        actos:
          type: array
          items:
            $ref: '#/components/schemas/acto'



